"use client";
import { useEffect, useState } from "react";

type Model = { id: string; name: string; provider: string; enabled: boolean; visible: boolean };
export default function VcaasSettingsPage() {
  const [token, setToken] = useState(""); const [models, setModels] = useState<Model[]>([]); const [keys, setKeys] = useState<{index:number;available:boolean;failures:number}[]>([]); const [error, setError] = useState("");
  async function load() { const r = await fetch("/api/admin/vcaas", { headers: { authorization: `Bearer ${token}` } }); const j = await r.json(); if (!r.ok) return setError(j.error); setModels(j.data.models); setKeys(j.data.keys); setError(""); }
  useEffect(() => { if (token) void load(); }, [token]);
  function update(index: number, patch: Partial<Model>) { setModels((list) => list.map((model, i) => i === index ? { ...model, ...patch } : model)); }
  async function save() { const r = await fetch("/api/admin/vcaas", { method: "PATCH", headers: { "Content-Type": "application/json", authorization: `Bearer ${token}` }, body: JSON.stringify({ models }) }); setError(r.ok ? "تم حفظ إعدادات النماذج." : "تعذر الحفظ"); }
  return <main className="min-h-screen bg-background text-foreground p-6"><div className="mx-auto max-w-4xl space-y-6"><header><p className="text-sm text-muted-foreground">إعدادات المشرف</p><h1 className="text-3xl font-semibold">نماذج VCaaS والمفاتيح</h1><p className="mt-2 text-muted-foreground">هذه الصفحة غير مرتبطة بواجهة الزوار. لا يتم عرض المفاتيح، بل حالتها فقط.</p></header><section className="rounded-xl border bg-card p-5 space-y-3"><label className="text-sm font-medium" htmlFor="admin-token">رمز المشرف</label><input id="admin-token" type="password" value={token} onChange={(e) => setToken(e.target.value)} placeholder="VCAAS_ADMIN_TOKEN" className="w-full rounded-md border bg-background px-3 py-2" /><button onClick={() => void load()} className="rounded-md bg-primary px-4 py-2 text-primary-foreground">تحميل الإعدادات</button>{error && <p className="text-sm text-muted-foreground">{error}</p>}</section><section className="rounded-xl border bg-card p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">صحة المفاتيح</h2><p className="text-sm text-muted-foreground">يدعم المفتاح الأساسي حتى 100 مفتاح احتياطي.</p></div><span className="text-sm">{keys.filter((key) => key.available).length}/{keys.length} متاح</span></div><div className="mt-4 flex flex-wrap gap-2">{keys.map((key) => <span key={key.index} className={`rounded-full px-3 py-1 text-xs ${key.available ? "bg-emerald-100 text-emerald-800" : "bg-amber-100 text-amber-800"}`}>API {key.index}{key.failures ? ` · ${key.failures} فشل` : ""}</span>)}</div></section><section className="rounded-xl border bg-card p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">النماذج</h2><button onClick={() => setModels([...models, { id: `custom-${Date.now()}`, name: "نموذج جديد", provider: "Totalum", enabled: true, visible: false }])} className="rounded-md border px-3 py-2 text-sm">إضافة نموذج</button></div><div className="mt-4 space-y-3">{models.map((model, index) => <div key={model.id} className="grid gap-2 rounded-lg border p-3 md:grid-cols-[1fr_1fr_auto_auto]"><input value={model.name} onChange={(e) => update(index, { name: e.target.value })} className="rounded border bg-background px-2 py-1" /><input value={model.provider} onChange={(e) => update(index, { provider: e.target.value })} className="rounded border bg-background px-2 py-1" /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={model.enabled} onChange={(e) => update(index, { enabled: e.target.checked })} /> تشغيل</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={model.visible} onChange={(e) => update(index, { visible: e.target.checked })} /> ظاهر للمستخدم</label></div>)}</div><button onClick={() => void save()} className="mt-4 rounded-md bg-primary px-4 py-2 text-primary-foreground">حفظ التغييرات</button></section></div></main>;
}
